# Site settings
title: Data Science Cliff Notes
tagline: Analytics the Easy Way
email: plbanalyze@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data Science Cliff Notes is data science for the rest of us. We break
  down key data science concepts down, and show how data science 
  techniques can help you be more strategic at your job.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "plbanalyze@gmail.com" # the base hostname & protocol for your site
github_username:  pkafei

# Build settings
markdown: kramdown
